### ISSUE TITLE
Does not clear after insert

### ISSUE THREAD

**Issue by benjick** [djhi/meteor-autoform-file-materialize#1]
Hey

The image doesn't clear after insert (the preview), but it can't be used again. 

See image below

![2015-04-17 14_07_44-infoadmin](https://cloud.githubusercontent.com/assets/430872/7201756/2cbabc08-e50b-11e4-9a3d-c49b6cdbff8b.png)

**Comment by SlashzeroOfficial** [comment]
I am also facing a similar issue.
Any solution for this?

Thanks

**Comment by ryanbuiltthat** [comment]
I had this issue too. My solution is pretty hacky and I hope a better one can be found but this seems to work for now. 

My form is set to use a method, that method returns true if successful. I then just added a hook to the form and if true programatically trigger the `click` even on the `Remove` link. Like I said it's pretty hacky but gets the job done.

```
var myHooks = {
    onSuccess: function(formType, result) {
        if(result){
            $(".file-upload-clear").trigger("click");
        }
    }
};


AutoForm.hooks({
    myForm: myHooks
});
```

Hope this helps!

**Comment by djhi** [comment]
Future work on this package has been transferred [here](https://github.com/mozfet/meteor-autoform-file-materialize).
