### ISSUE TITLE
Please catch up with yogiben fileupload

### ISSUE THREAD

**Issue by serkandurusoy** [djhi/meteor-autoform-file-materialize#4]
Take a look at this

https://github.com/yogiben/meteor-autoform-file/issues/51#issuecomment-131993883

There are improvements such as this on the original repo so it would be great if this _materialized fork_ were up to date as well.

**Comment by djhi** [comment]
Thx for the info. I'll try to do that as soon as I have the time

**Comment by serkandurusoy** [comment]
Great, thanks!

**Comment by serkandurusoy** [comment]
@djhi @Chun-Yang would you perhaps consider sharing your common autoform-material love for updating this as well :)

**Comment by djhi** [comment]
Do you want access to this repo ?

**Comment by serkandurusoy** [comment]
Hi, would love to, unfortunately I'm merely an, althogh avid, user of the package. I wish I were familiar with the inner workings :(

**Comment by djhi** [comment]
Future work on this package has been transferred [here](https://github.com/mozfet/meteor-autoform-file-materialize).
