### ISSUE TITLE
Dependency constraint failure

### ISSUE THREAD

**Issue by RamyElkest** [djhi/meteor-autoform-file-materialize#5]
While selecting package versions:
   error: Conflict: Constraint less@1.0.11 is not satisfied by less 2.5.1.
   Constraints on package "less":
- less@=2.5.1 <- top level
- less@2.5.0_1 <- accounts-ui 1.1.6
- less@2.5.0_1 <- accounts-ui-unstyled 1.1.8 <- accounts-ui 1.1.6
- less@1.0.11 <- gildaspk:autoform-file-materialize 0.0.7

which i suppose is similar to https://github.com/yogiben/meteor-autoform-file/issues/64

and would be resolved by https://github.com/djhi/meteor-autoform-file-materialize/issues/4

**Comment by djhi** [comment]
Future work on this package has been transferred [here](https://github.com/mozfet/meteor-autoform-file-materialize).
